{% set name = "python-graphblas" %}
{% set version = "2022.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python-graphblas-{{ version }}.tar.gz
  sha256: 54a6af858235cb3a27aad5d290e444df68b0cc6df8cd42e0e2ac25b85cd45d9d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - donfig
    - numba
    - python >=3.8
    - python-suitesparse-graphblas >=7.3.0.2,<7.4
    - pyyaml

test:
  imports:
    - graphblas
    - graphblas.agg
  commands:
    - pip check
    - python -c "from graphblas import Matrix"
  requires:
    - pip

about:
  home: https://github.com/python-graphblas/python-graphblas
  summary: Python interface to GraphBLAS
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  description: |
    Python wrapper around GraphBLAS. Currently only supports SuiteSparse::GraphBLAS.
    Goal is to be a Pythonic way to write beautiful, efficient graph algorithms
    in the language of linear algebra.
  dev_url: https://github.com/python-graphblas/python-graphblas

extra:
  recipe-maintainers:
    - eriknw
    - jim22k
