{% set name = "python-graphblas" %}
{% set version = "2023.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python-graphblas-{{ version }}.tar.gz
  sha256: a08b807ea4a8ca1a97592cf38730c1da93d4150929d79ae6cd00021b2b1f1f15

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=64
    - setuptools-git-versioning
    - pip
  run:
    - python >=3.8
    - python-suitesparse-graphblas >=7.4.0.0,<7.5
    - numpy >=1.21
    - numba >=0.55
    - donfig >=0.6
    - pyyaml >=5.4

test:
  imports:
    - graphblas
    - graphblas.agg
  commands:
    - pip check
    - python -c "from graphblas import Matrix"
  requires:
    - pip

about:
  home: https://github.com/python-graphblas/python-graphblas
  summary: 'Python library for GraphBLAS: high-performance sparse linear algebra for scalable graph analytics'
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  description: |
    Python wrapper around GraphBLAS. Currently only supports SuiteSparse::GraphBLAS.
    Goal is to be a Pythonic way to write beautiful, efficient graph algorithms
    in the language of linear algebra.
  dev_url: https://github.com/python-graphblas/python-graphblas

extra:
  recipe-maintainers:
    - eriknw
    - jim22k
