{% set name = "python-graphblas" %}
{% set version = "2022.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python-graphblas-{{ version }}.tar.gz
  sha256: c94419371e5c224e298352122694ed14d9bb3572158d7dc0240a6509f9118ca4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - donfig
    - numba
    - python >=3.8
    - python-suitesparse-graphblas >=7.1.0.0,<7.2
    - pyyaml

test:
  imports:
    - graphblas
    - graphblas._ss
  commands:
    - pip check
    - python -c "from graphblas import Matrix"
  requires:
    - pip

about:
  home: https://github.com/python-graphblas/python-graphblas
  summary: Python interface to GraphBLAS
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  description: |
    Python wrapper around GraphBLAS. Currently only supports SuiteSparse::GraphBLAS.
    Goal is to be a Pythonic way to write beautiful, efficient graph algorithms
    in the language of linear algebra.
  dev_url: https://github.com/python-graphblas/python-graphblas

extra:
  recipe-maintainers:
    - eriknw
    - jim22k
